=== ZePedroFernandes/LEI_PEI/Ficha 1/Ingredientes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    
    <xs:simpleType name = "categorys">
        <xs:restriction base = "xs:string">
            <xs:enumeration value="Vegetal" />
            <xs:enumeration value="Dairy" />
            <xs:enumeration value="Sauce" />
            <xs:enumeration value="Herb" />
            <xs:enumeration value="Meat" />
            <xs:enumeration value="Sauce" />
            <xs:enumeration value="Pasta" />
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="units">
        <xs:restriction base = "xs:string">
            <xs:enumeration value = "grams"/>
            <xs:enumeration value = "milliliters"/>
            <xs:enumeration value = "unit"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:complexType name = "Ingredient">
        <xs:sequence>
            <xs:element name = "name" type = "xs:string"/>
            <xs:element name = "category" type = "categorys"/>
            <xs:element name = "calories" type = "xs:int"/>
            <xs:element name = "unit" type = "units"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name = "Ingredients">
        <xs:sequence maxOccurs="unbounded">
            <xs:element name="Ingredient" type = "Ingredient"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:element name="Ingredients" type = "Ingredients"/>
    
</xs:schema>

=== ZePedroFernandes/LEI_PEI/Ficha1/Ingredientes.xml
<?xml version="1.0" encoding="UTF-8"?>
<Ingredients xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation = "Ingredientes.xsd">
    <Ingredient>
        <name>Tomato</name>
        <category>Vegetal</category>
        <calories>18</calories>
        <unit>grams</unit>
    </Ingredient>
    
    <Ingredient>
        <name>Spinach</name>
        <category>Vegetal</category>
        <calories>18</calories>
        <unit>grams</unit>
    </Ingredient>
        
    <Ingredient>
        <name>Cheese</name>
        <category>Dairy</category>
        <calories>25</calories>
        <unit>grams</unit>
    </Ingredient>
        
    <Ingredient>
        <name>Tomato Sauce</name>
        <category>Sauce</category>
        <calories>40</calories>
        <unit>milliliters</unit>
    </Ingredient>
        
    <Ingredient>
        <name>Oregano</name>
        <category>Herb</category>
        <calories>45</calories>
        <unit>grams</unit>
    </Ingredient>
        
    <Ingredient>
        <name>Chicken</name>
        <category>Meat</category>
        <calories>32</calories>
        <unit>grams</unit>   
    </Ingredient>
        
    <Ingredient>
        <name>Onion Sauce</name>
        <category>Sauce</category>
        <calories>55</calories>
        <unit>milliliters</unit>
    </Ingredient>
        
    <Ingredient>
        <name>Pasta</name>
        <category>Pasta</category>
        <calories>43</calories>
        <unit>milliliters</unit>
    </Ingredient>
        
</Ingredients>
