=== ZePedroFernandes/LEI_PEI/Ficha 3/Ex1/ingredientTypes.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
    xmlns:c = "zepedro/commonTypes"
    xmlns = "zepedro/ingredientTypes"
    targetNamespace="zepedro/ingredientTypes">
    <xs:import namespace="zepedro/commonTypes" schemaLocation="commonTypes.xsd"/>
    
    <xs:element name="Ingredients">
        <xs:annotation>
            <xs:documentation>Root element</xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence maxOccurs="unbounded">
                <xs:element ref="ingredient"></xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
    <xs:simpleType name = "categoryType">
        <xs:annotation>
            <xs:documentation>Rule that defines available categorys</xs:documentation>
        </xs:annotation>
        <xs:restriction base = "xs:string">
            <xs:enumeration value="Vegetal" />
            <xs:enumeration value="Dairy" />
            <xs:enumeration value="Sauce" />
            <xs:enumeration value="Herb" />
            <xs:enumeration value="Meat" />
            <xs:enumeration value="Sauce" />
            <xs:enumeration value="Pasta" />
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="ingredientName">
        <xs:annotation>
            <xs:documentation>Rule that defines all ingredient's names</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:enumeration value="Spinach"/>
            <xs:enumeration value="Cheese"/>
            <xs:enumeration value="Tomato Sauce"/>
            <xs:enumeration value="Oregano"/>
            <xs:enumeration value="Chicken"/>
            <xs:enumeration value="Onion Sauce"/>
            <xs:enumeration value="Pasta"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:complexType name="ingredientType">
        <xs:annotation>
            <xs:documentation>Rule that defines the ingredients</xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="name" type="ingredientName"/>
            <xs:element name="category" type="categoryType"/>
            <xs:element name="calories" type= "xs:string"/>
            <xs:element ref="c:unit"/>
        </xs:sequence>
    </xs:complexType>
    
    <!-- Elemento global -->
    <xs:element name="ingredient" type="ingredientType">
        <xs:annotation>
            <xs:documentation>ingredient global element</xs:documentation>
        </xs:annotation>
    </xs:element>
    
    <!-- Elemento global -->
    <xs:element name="ingredientName" type="ingredientName">
        <xs:annotation>
            <xs:documentation>ingredient's name global element</xs:documentation>
        </xs:annotation>
    </xs:element>
    
</xs:schema>

=== ZePedroFernandes/LEI_PEI/Ficha 3/Ex1/ingredients.xml
<?xml version="1.0" encoding="UTF-8"?>
<Ingredients xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation = "ingredientTypes.xsd" 
    xmlns = "zepedro/ingredientTypes"
    xmlns:c = "zepedro/commonTypes">
    <ingredient>
        <name>Tomato Sauce</name>
        <category>Vegetal</category>
        <calories>18</calories>
        <c:unit>grams</c:unit>
    </ingredient>
    
    <ingredient>
        <name>Spinach</name>
        <category>Vegetal</category>
        <calories>18</calories>
        <c:unit>grams</c:unit>
    </ingredient>
    
    <ingredient>
        <name>Cheese</name>
        <category>Dairy</category>
        <calories>25</calories>
        <c:unit>grams</c:unit>
    </ingredient>
    
    <ingredient>
        <name>Tomato Sauce</name>
        <category>Sauce</category>
        <calories>40</calories>
        <c:unit>milliliters</c:unit>
    </ingredient>
    
    <ingredient>
        <name>Oregano</name>
        <category>Herb</category>
        <calories>45</calories>
        <c:unit>grams</c:unit>
    </ingredient>
    
    <ingredient>
        <name>Chicken</name>
        <category>Meat</category>
        <calories>32</calories>
        <c:unit>grams</c:unit>   
    </ingredient>
    
    <ingredient>
        <name>Onion Sauce</name>
        <category>Sauce</category>
        <calories>55</calories>
        <c:unit>milliliters</c:unit>
    </ingredient>
    
    <ingredient>
        <name>Pasta</name>
        <category>Pasta</category>
        <calories>43</calories>
        <c:unit>milliliters</c:unit>
    </ingredient>
    
</Ingredients>
